### PR TITLE
upgrade all packages and mount order

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ivandavidov** [comment]
Do you have any particular reason why you decided to change the mount order?

**Comment by ghost** [comment]
/proc must be mount first, because this mount point provides info and services from kernel. Also this order recommended for better working

**Comment by ivandavidov** [comment]
Could you please refer to some online documentation where it is stated that ``/proc`` should be mounted first and that your proposed mount order is the recommended way to do it?

``/dev``, ``/proc`` and ``sys`` can be mounted in any order and this has been proven to work in the MLL project. The ``/proc`` mountpoint provides useful information to the userland and both in MLS and MLL these core filesystems are mounted at the very beginning (long before the userland is involved), so there is no need to mount them in any particular order.

Also, you should have in mind that MLS provides shell script file, as well as README document in which the same steps are present. Your PR updates the shell script but leaves the README intact. In this case the shell script file and the README commands will provide different mount order which is not good.

Please have in mind that just because you have an idea, it is not enough just to provide some code as PR. You have to be consistent and update all relevant sources and also give reasonable explanation why you do these changes.

I have no preferences about the mount order and I will approve your PR as as soon as you update the README accordingly.

**Comment by ivandavidov** [comment]
I'm closing the PR since the readme file hasn't been updated.

**Pull request closed without merging**
