### PR TITLE
Code to reuse downloaded tarballs

### PR DESCRIPTION
**Pull request by antoniusmisfit**
Added code to reuse already downloaded tarballs, saving time on recompiles.

### CODE REVIEW

**Comment by ivandavidov** [comment]
Better way is to utilize the ``-c`` option. You can see how it works [here](https://github.com/ivandavidov/minimal/blob/master/src/minimal_overlay/bundles/cf_cli/01_get.sh#L21).

I'll decline the pull request because the whole purpose of this project (and this script) is to keep the whole process as simple and as linear as possible. Intoducing ``if`` statements doesn't make the script simpler.

**Comment by antoniusmisfit** [comment]
Ah, I see. I'll test the -c approach on my own Linux project. Thanks for the tip!

**Comment by ivandavidov** [comment]
When you use ``wget`` with ``-c``, wget checks whether the downloaded file size matches the file size reported by the server. If both file sizes match, this means there is no need to re-download the file. If the downloaded file size is smaller, then ``wget`` is smart enough to continue from where it last stopped.

**Comment by antoniusmisfit** [comment]
Yup, the -c option works like a charm.

**Pull request closed without merging**
